### ISSUE TITLE
Minimal Docker image

### ISSUE THREAD

**Issue by muety** [n1try/gitcount#2]
Provide `gitcount` as Docker image for users without Go installed.
Also generate binaries for standalone use.

**Comment by bhavin192** [comment]
I would like to work on this.

**Comment by muety** [comment]
Go for it!

**Comment by gonzalesraul** [comment]
PR #5 opened.

By the way, still need some automation but you can find the result already on docker hub at:

https://hub.docker.com/r/gitcount/gitcount/

**Comment by bhavin192** [comment]
I was working on this one :(

**Comment by muety** [comment]
@bhavin192 I'm sorry 😐 And thank you for your effort anyway!

Resolved by #5
